/*
 * Creative Commons Attribution Non-Commercial Share Alike
 */
package ui;

import javax.swing.ImageIcon;

public class BoardGUI extends javax.swing.JFrame {

    /** Creates new form BoardGUI */
    public BoardGUI() {
        initComponents();
        setLocationRelativeTo(null);
        createSquares(core.Board.BOARD_LENGTH,core.Board.BOARD_WIDTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/ui/images/logo.jpg")).getImage());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoardGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private javax.swing.JButton[][] squares;
    
    private void createSquares(int boardlength,int boardwidth) {
        squares = new javax.swing.JButton[boardlength][boardwidth];
        for(int x=0;x<boardlength;x++) {
            for(int y=0;y<boardwidth;y++) {
                squares[x][y] = new javax.swing.JButton();
            }
        }
    }

}
